version: '3.8'

services:
  db-orders:
    image: postgres:16.1
    container_name: db-orders
    restart: always
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'orders'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./metric_files/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana # Asegurarse de que el volumen se define correctamente
    depends_on:
      - prometheus

  es-publico-app:
    image: dannyelyankee/es-publico-app:v4
    container_name: es-publico-app
    restart: always
    depends_on:
      - db-orders
    ports:
      - '8080:8080'
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_URL=${DB_URL}
      - DB_PASSWORD=${DB_PASSWORD}
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}

volumes:
  pgdata:
  grafana-data:
