spring:
   port: 8080
   datasource:
      username: ${DB_USERNAME}
      url: ${DB_URL}
      password: ${DB_PASSWORD}
   application:
      name: app

management:
   endpoints:
      web:
         exposure:
            include: prometheus
   metrics:
      export:
         prometheus:
            enabled: true

global:
   scrape_interval: 10s

scrape_configs:
-  job_name: spring-boot-actuator
   metrics_path: /actuator/prometheus
   static_configs:
   -  targets:
      - localhost:8080

logging:
   level:
      org:
         springframework:
            security: DEBUG

token:
   secret_key: ${TOKEN_SECRET_KEY}